# This init configuration file is generated by Makefile
# DO NOT making changes here!

org_id="${TF_VAR_org_id}"
billing_id="${TF_VAR_billing_id}"
project_id="${TF_VAR_project_id}"
secrets_path="${TF_VAR_secrets_path}"
google_credentials_file="${TF_VAR_google_credentials_file}"
google_admin_project_id="${TF_VAR_google_admin_project_id}"
remote_state_bucket="${TF_VAR_remote_state_bucket}"
remote_state_path="${TF_VAR_remote_state_path}"